name: "Pull Request Linter"
description: "Ensures your PR title matches a given regex"
author: "MorrisonCole / Cultivate"
branding:
  icon: "check"
  color: "green"
inputs:
  title:
    description: 'JSON list of regexes and error messages. Example: [{"regex": "foo", "comment": "Title must contain foo"}]'
    required: true
    default: "[]"
  body:
    description: 'JSON list of regexes and error messages. Example: [{"regex": "foo", "comment": "Body must contain foo"}]'
    required: true
    default: "[]"
runs:
  using: "docker"
  image: "Dockerfile"
